version: '3.8'
services:
  mongodb:
    container_name: mongodb-maquinua-container
    image: mongo:6.0.13 
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    networks:
      - maquinua-backend-network
    stdin_open: true
    tty: true 
    restart: always

  backend-maquinua:
    container_name: backend-maquinua-container
    image: node:18
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongodb
    networks:
      - maquinua-backend-network
    restart: always

networks:
  maquinua-backend-network:
    driver: bridge

